### ISSUE TITLE
Timout when trying to register a new user

### ISSUE THREAD

**Issue by rxrdev** [nekonako/moechat#1]
I'm trying to register a new user and the request `POST: https://nekonako.space/register` is canceled because it takes more than 5 seconds to get the response.

Possible related to the axios config: https://github.com/nekonako/moechat/blob/master/mashu/src/service/api.ts#L6

![image](https://user-images.githubusercontent.com/40596596/143398254-2ba2a5df-83d6-4816-91e5-8c68c8183c57.png)

**Comment by nekonako** [comment]
hi @RazvanRauta  thanks for the issue report

you konw my vm is 100% of cpu usage, i dont know why.
but i sus goroutines that is handling the websocket connections.

i'm still new in golang world and this project is versy premature. very bad error handling and more.
and i decided to don't care XD

btw it's back to normal, please try

**Comment by rxrdev** [comment]
@nekonako Same problem. Your Demo is published on [reactjsexample](https://reactjsexample.com/a-simple-chat-app-with-websocket-golang-and-react-js/) and also here [app.daily](https://app.daily.dev/posts/UhHitSjQU), and maybe there is too much traffic? 

I see a 500 now from the backend: `dial tcp: lookup postgre on 127.0.0.11:53: no such host`

![image](https://user-images.githubusercontent.com/40596596/143445057-79a4eebf-06db-479d-8ef6-af15e82041f2.png)

**Comment by nekonako** [comment]
i never published it on any site.
hmm is it possible that these sites are automatically crawled from github ?

**Comment by nekonako** [comment]
sorry @RazvanRauta,  i'm forget to restart the postgre container
